"""initial schema

Revision ID: 39a54fdf76ff
Revises: 
Create Date: 2026-06-21 00:14:47.550008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39a54fdf76ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('college_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_ru', sa.String(length=300), nullable=True),
    sa.Column('name_kz', sa.String(length=300), nullable=True),
    sa.Column('director_full_name', sa.String(length=200), nullable=True),
    sa.Column('director_basis', sa.String(length=200), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('bin', sa.String(length=20), nullable=True),
    sa.Column('iik', sa.String(length=40), nullable=True),
    sa.Column('bank_name', sa.String(length=200), nullable=True),
    sa.Column('bank_address', sa.String(length=200), nullable=True),
    sa.Column('bank_bik', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('phone', sa.String(length=60), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('template_path', sa.String(length=500), nullable=True),
    sa.Column('contract_prefix', sa.String(length=10), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract_counters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('last_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year')
    )
    op.create_table('partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_name', sa.String(length=300), nullable=False),
    sa.Column('bin', sa.String(length=20), nullable=True),
    sa.Column('legal_address', sa.String(length=500), nullable=True),
    sa.Column('actual_address', sa.String(length=500), nullable=True),
    sa.Column('director_full_name', sa.String(length=200), nullable=True),
    sa.Column('director_position', sa.String(length=200), nullable=True),
    sa.Column('director_basis', sa.String(length=300), nullable=True),
    sa.Column('contact_person', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=60), nullable=True),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('specialty', sa.String(length=200), nullable=True),
    sa.Column('seats_count', sa.Integer(), nullable=True),
    sa.Column('contract_status', sa.String(length=40), nullable=True),
    sa.Column('contract_valid_until', sa.Date(), nullable=True),
    sa.Column('bank_name', sa.String(length=200), nullable=True),
    sa.Column('bank_bik', sa.String(length=40), nullable=True),
    sa.Column('bank_iik', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partners_bin'), ['bin'], unique=True)
        batch_op.create_index(batch_op.f('ix_partners_organization_name'), ['organization_name'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('iin', sa.String(length=20), nullable=True),
    sa.Column('group_name', sa.String(length=60), nullable=True),
    sa.Column('specialty', sa.String(length=200), nullable=True),
    sa.Column('course', sa.Integer(), nullable=True),
    sa.Column('practice_start', sa.Date(), nullable=True),
    sa.Column('practice_end', sa.Date(), nullable=True),
    sa.Column('college_supervisor', sa.String(length=200), nullable=True),
    sa.Column('partner_supervisor', sa.String(length=200), nullable=True),
    sa.Column('partner_id', sa.Integer(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('id_card_number', sa.String(length=60), nullable=True),
    sa.Column('id_card_issued_by', sa.String(length=200), nullable=True),
    sa.Column('home_address', sa.String(length=300), nullable=True),
    sa.Column('phone', sa.String(length=60), nullable=True),
    sa.Column('legal_rep_full_name', sa.String(length=200), nullable=True),
    sa.Column('legal_rep_iin', sa.String(length=20), nullable=True),
    sa.Column('legal_rep_phone', sa.String(length=60), nullable=True),
    sa.Column('education_program', sa.String(length=300), nullable=True),
    sa.Column('specialty_code', sa.String(length=60), nullable=True),
    sa.Column('enrollment_year', sa.Integer(), nullable=True),
    sa.Column('practice_type', sa.String(length=120), nullable=True),
    sa.Column('form_of_study', sa.String(length=60), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_full_name'), ['full_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_group_name'), ['group_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_iin'), ['iin'], unique=True)

    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('contract_date', sa.Date(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('docx_path', sa.String(length=500), nullable=True),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('signed_scan_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contracts_number'), ['number'], unique=True)
        batch_op.create_index(batch_op.f('ix_contracts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_contracts_year'), ['year'], unique=False)

    op.create_table('signatures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('signer_role', sa.String(length=40), nullable=False),
    sa.Column('signer_full_name', sa.String(length=200), nullable=True),
    sa.Column('signer_iin_or_bin', sa.String(length=20), nullable=True),
    sa.Column('signer_serial', sa.String(length=80), nullable=True),
    sa.Column('signer_certificate_pem', sa.Text(), nullable=True),
    sa.Column('cms_signature', sa.Text(), nullable=False),
    sa.Column('signed_payload_sha256', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_id', 'signer_role', name='uq_signature_contract_role')
    )
    op.create_table('signing_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('signer_role', sa.String(length=20), nullable=False),
    sa.Column('recipient_name', sa.String(length=200), nullable=True),
    sa.Column('recipient_email', sa.String(length=160), nullable=True),
    sa.Column('recipient_iin_or_bin', sa.String(length=20), nullable=True),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('viewed_at', sa.DateTime(), nullable=True),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('signature_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['signature_id'], ['signatures.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signing_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signing_requests_contract_id'), ['contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signing_requests_token'), ['token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signing_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signing_requests_token'))
        batch_op.drop_index(batch_op.f('ix_signing_requests_contract_id'))

    op.drop_table('signing_requests')
    op.drop_table('signatures')
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contracts_year'))
        batch_op.drop_index(batch_op.f('ix_contracts_status'))
        batch_op.drop_index(batch_op.f('ix_contracts_number'))

    op.drop_table('contracts')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_iin'))
        batch_op.drop_index(batch_op.f('ix_students_group_name'))
        batch_op.drop_index(batch_op.f('ix_students_full_name'))

    op.drop_table('students')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partners_organization_name'))
        batch_op.drop_index(batch_op.f('ix_partners_bin'))

    op.drop_table('partners')
    op.drop_table('contract_counters')
    op.drop_table('college_settings')
    # ### end Alembic commands ###
