"""enrollment contracts (educational services)

Revision ID: bcf6df38fb68
Revises: 39a54fdf76ff
Create Date: 2026-06-21 09:28:22.674600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcf6df38fb68'
down_revision = '39a54fdf76ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrollment_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=60), nullable=True),
    sa.Column('contract_date', sa.Date(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('applicant_full_name', sa.String(length=200), nullable=False),
    sa.Column('applicant_iin', sa.String(length=20), nullable=True),
    sa.Column('applicant_birth_date', sa.Date(), nullable=True),
    sa.Column('applicant_gender', sa.String(length=10), nullable=True),
    sa.Column('applicant_id_doc_type', sa.String(length=60), nullable=True),
    sa.Column('applicant_id_doc_number', sa.String(length=60), nullable=True),
    sa.Column('applicant_id_doc_issued_by', sa.String(length=200), nullable=True),
    sa.Column('applicant_id_doc_issued_date', sa.Date(), nullable=True),
    sa.Column('applicant_address_city', sa.String(length=120), nullable=True),
    sa.Column('applicant_address_district', sa.String(length=120), nullable=True),
    sa.Column('applicant_address_street', sa.String(length=200), nullable=True),
    sa.Column('applicant_address_house', sa.String(length=60), nullable=True),
    sa.Column('applicant_phone', sa.String(length=60), nullable=True),
    sa.Column('applicant_home_phone', sa.String(length=60), nullable=True),
    sa.Column('applicant_email', sa.String(length=160), nullable=True),
    sa.Column('parent_full_name', sa.String(length=200), nullable=True),
    sa.Column('parent_relation', sa.String(length=60), nullable=True),
    sa.Column('parent_iin', sa.String(length=20), nullable=True),
    sa.Column('parent_id_doc_number', sa.String(length=60), nullable=True),
    sa.Column('parent_id_doc_issued_by', sa.String(length=200), nullable=True),
    sa.Column('parent_address', sa.String(length=400), nullable=True),
    sa.Column('parent_phone', sa.String(length=60), nullable=True),
    sa.Column('parent_email', sa.String(length=160), nullable=True),
    sa.Column('specialty', sa.String(length=200), nullable=True),
    sa.Column('specialty_code', sa.String(length=60), nullable=True),
    sa.Column('qualification', sa.String(length=200), nullable=True),
    sa.Column('education_base', sa.String(length=10), nullable=True),
    sa.Column('study_form', sa.String(length=60), nullable=True),
    sa.Column('course', sa.Integer(), nullable=True),
    sa.Column('tuition_year_amount', sa.Integer(), nullable=True),
    sa.Column('contract_docx_path', sa.String(length=500), nullable=True),
    sa.Column('contract_pdf_path', sa.String(length=500), nullable=True),
    sa.Column('consent_docx_path', sa.String(length=500), nullable=True),
    sa.Column('consent_pdf_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('enrollment_contracts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enrollment_contracts_applicant_full_name'), ['applicant_full_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrollment_contracts_applicant_iin'), ['applicant_iin'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrollment_contracts_number'), ['number'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrollment_contracts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrollment_contracts_year'), ['year'], unique=False)

    op.create_table('enrollment_signatures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('document', sa.String(length=20), nullable=False),
    sa.Column('signer_party', sa.String(length=20), nullable=False),
    sa.Column('signer_full_name', sa.String(length=200), nullable=True),
    sa.Column('signer_iin_or_bin', sa.String(length=20), nullable=True),
    sa.Column('signer_serial', sa.String(length=80), nullable=True),
    sa.Column('signer_certificate_pem', sa.Text(), nullable=True),
    sa.Column('cms_signature', sa.Text(), nullable=False),
    sa.Column('signed_payload_sha256', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollment_contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enrollment_id', 'document', 'signer_party', name='uq_enroll_sig_doc_party')
    )
    op.create_table('enrollment_signing_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('signer_party', sa.String(length=20), nullable=False),
    sa.Column('recipient_name', sa.String(length=200), nullable=True),
    sa.Column('recipient_iin', sa.String(length=20), nullable=True),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('viewed_at', sa.DateTime(), nullable=True),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollment_contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('enrollment_signing_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enrollment_signing_requests_enrollment_id'), ['enrollment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrollment_signing_requests_token'), ['token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollment_signing_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enrollment_signing_requests_token'))
        batch_op.drop_index(batch_op.f('ix_enrollment_signing_requests_enrollment_id'))

    op.drop_table('enrollment_signing_requests')
    op.drop_table('enrollment_signatures')
    with op.batch_alter_table('enrollment_contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enrollment_contracts_year'))
        batch_op.drop_index(batch_op.f('ix_enrollment_contracts_status'))
        batch_op.drop_index(batch_op.f('ix_enrollment_contracts_number'))
        batch_op.drop_index(batch_op.f('ix_enrollment_contracts_applicant_iin'))
        batch_op.drop_index(batch_op.f('ix_enrollment_contracts_applicant_full_name'))

    op.drop_table('enrollment_contracts')
    # ### end Alembic commands ###
